In [18]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [19]:
df=pd.read_csv('cleaned_data.csv')

In [20]:
#divide into x and y
X= df.drop(columns=['Outcome'])
y=df[['Outcome']]

In [21]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X = pd.DataFrame(data=sc.fit_transform(X),columns=X.columns)


In [22]:
#divide into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=0,stratify=y)


In [23]:
print(y_train['Outcome'].value_counts())
print(y_test['Outcome'].value_counts())


Outcome
0    450
1    241
Name: count, dtype: int64
Outcome
0    50
1    27
Name: count, dtype: int64


In [24]:
pip install imblearn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [25]:
#create balanced data in trainingusing SMOTE
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
X_resampled,y_resampled=smote.fit_resample(X_train,y_train)

In [26]:
y_resampled['Outcome'].value_counts()

Outcome
0    450
1    450
Name: count, dtype: int64

In [27]:
#build model and train
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)

[[41  9]
 [ 6 21]]
0.8051948051948052


In [28]:
#build model and train
from sklearn.tree import DecisionTreeClassifier
model_dt= DecisionTreeClassifier(criterion='gini')
model_dt.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model_dt.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)

[[45  5]
 [11 16]]
0.7922077922077922


In [29]:
#Build and train model
from sklearn.ensemble import RandomForestClassifier
model_rf= RandomForestClassifier(n_estimators=101)
model_rf.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model_rf.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)

[[45  5]
 [10 17]]
0.8051948051948052


In [30]:
#build and train model
from sklearn.neighbors import KNeighborsClassifier
model_knn= KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
model_knn.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model_knn.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)

[[38 12]
 [ 7 20]]
0.7532467532467533


In [31]:
#build and train model
from sklearn.naive_bayes import GaussianNB
model_nb= GaussianNB()
model_nb.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model_nb.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)

[[40 10]
 [ 9 18]]
0.7532467532467533


In [32]:
#build and train model
from sklearn.svm import SVC
model_svc = SVC(kernel='rbf')
model_svc.fit(X_resampled,y_resampled)

#evaluate model
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred= model_svc.predict(X_test)
y_pred= pd.DataFrame(data=y_pred,columns=['Prediction'])
result= pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
cm= confusion_matrix(result['Outcome'],result['Prediction'])
score= accuracy_score(result['Outcome'],result['Prediction'])
print(cm)
print(score)


[[43  7]
 [ 6 21]]
0.8311688311688312


In [35]:
#accuracy score of random forest algo 
import pickle
pickle.dump(model_svc,open('model_svc.pkl','wb'))
pickle.dump(sc,open('sc.pkl','wb'))

In [36]:
columns=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
myinput=[[10,150,80,35,130,30,0.65,55]]
myinput= pd.DataFrame(data=sc.transform(myinput),columns=columns)
myinput=pd.DataFrame(data=sc.transform(myinput),columns=columns)
result=model_rf.predict(myinput)
if result[0] == 0:
    print("No,Patient is not diabetic")
else:
    print("Yes,Patient is diabetic")

No,Patient is not diabetic
